"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[53381],{603905:(e,n,t)=>{t.d(n,{Zo:()=>c,kt:()=>m});var r=t(667294);function o(e,n,t){return n in e?Object.defineProperty(e,n,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[n]=t,e}function a(e,n){var t=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);n&&(r=r.filter((function(n){return Object.getOwnPropertyDescriptor(e,n).enumerable}))),t.push.apply(t,r)}return t}function i(e){for(var n=1;n<arguments.length;n++){var t=null!=arguments[n]?arguments[n]:{};n%2?a(Object(t),!0).forEach((function(n){o(e,n,t[n])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(t)):a(Object(t)).forEach((function(n){Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(t,n))}))}return e}function s(e,n){if(null==e)return{};var t,r,o=function(e,n){if(null==e)return{};var t,r,o={},a=Object.keys(e);for(r=0;r<a.length;r++)t=a[r],n.indexOf(t)>=0||(o[t]=e[t]);return o}(e,n);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);for(r=0;r<a.length;r++)t=a[r],n.indexOf(t)>=0||Object.prototype.propertyIsEnumerable.call(e,t)&&(o[t]=e[t])}return o}var l=r.createContext({}),p=function(e){var n=r.useContext(l),t=n;return e&&(t="function"==typeof e?e(n):i(i({},n),e)),t},c=function(e){var n=p(e.components);return r.createElement(l.Provider,{value:n},e.children)},u="mdxType",d={inlineCode:"code",wrapper:function(e){var n=e.children;return r.createElement(r.Fragment,{},n)}},h=r.forwardRef((function(e,n){var t=e.components,o=e.mdxType,a=e.originalType,l=e.parentName,c=s(e,["components","mdxType","originalType","parentName"]),u=p(t),h=o,m=u["".concat(l,".").concat(h)]||u[h]||d[h]||a;return t?r.createElement(m,i(i({ref:n},c),{},{components:t})):r.createElement(m,i({ref:n},c))}));function m(e,n){var t=arguments,o=n&&n.mdxType;if("string"==typeof e||o){var a=t.length,i=new Array(a);i[0]=h;var s={};for(var l in n)hasOwnProperty.call(n,l)&&(s[l]=n[l]);s.originalType=e,s[u]="string"==typeof e?e:o,i[1]=s;for(var p=2;p<a;p++)i[p]=t[p];return r.createElement.apply(null,i)}return r.createElement.apply(null,t)}h.displayName="MDXCreateElement"},278430:(e,n,t)=>{t.r(n),t.d(n,{assets:()=>l,contentTitle:()=>i,default:()=>d,frontMatter:()=>a,metadata:()=>s,toc:()=>p});var r=t(487462),o=(t(667294),t(603905));const a={},i="Exceptions",s={unversionedId:"python/python-intro/exceptions",id:"python/python-intro/exceptions",title:"Exceptions",description:"Should I Use Exceptions of Conditional Handling?",source:"@site/docs/python/python-intro/exceptions.md",sourceDirName:"python/python-intro",slug:"/python/python-intro/exceptions",permalink:"/python/python-intro/exceptions",draft:!1,editUrl:"https://github.com/deepaksood619/deepaksood619.github.io/tree/main/docs/python/python-intro/exceptions.md",tags:[],version:"current",lastUpdatedAt:1677955187,formattedLastUpdatedAt:"Mar 4, 2023",frontMatter:{},sidebar:"tutorialSidebar",previous:{title:"DateTime",permalink:"/python/python-intro/datetime"},next:{title:"File IO",permalink:"/python/python-intro/file-io"}},l={},p=[{value:"Should I Use Exceptions of Conditional Handling?",id:"should-i-use-exceptions-of-conditional-handling",level:2},{value:"What is an Exception",id:"what-is-an-exception",level:2},{value:"Why use exceptions",id:"why-use-exceptions",level:2},{value:"Raising an Excpetion",id:"raising-an-excpetion",level:2},{value:"Exceptions",id:"exceptions-1",level:2},{value:"Catch Exceptions",id:"catch-exceptions",level:2},{value:"Catch requests exception",id:"catch-requests-exception",level:2},{value:"Try Catch Finally block",id:"try-catch-finally-block",level:2},{value:"Try Catch Else Finally block",id:"try-catch-else-finally-block",level:2},{value:"Raise Exception",id:"raise-exception",level:2},{value:"Error vs Exception",id:"error-vs-exception",level:2},{value:"Built-in Exceptions",id:"built-in-exceptions",level:2},{value:"References",id:"references",level:2}],c={toc:p},u="wrapper";function d(e){let{components:n,...a}=e;return(0,o.kt)(u,(0,r.Z)({},c,a,{components:n,mdxType:"MDXLayout"}),(0,o.kt)("h1",{id:"exceptions"},"Exceptions"),(0,o.kt)("h2",{id:"should-i-use-exceptions-of-conditional-handling"},"Should I Use Exceptions of Conditional Handling?"),(0,o.kt)("p",null,'Python best practice is to use exceptions as a better way to handle "exceptional" cases. Unnecessary use ofif\'s may slow down your code. Although, keep in mind frequent "except" calls ',(0,o.kt)("a",{parentName:"p",href:"http://stackoverflow.com/questions/2522005/cost-of-exception-handlers-in-python"},"are even slower")," than plainifconditional handling, so you must use it wisely."),(0,o.kt)("p",null,"A try/except block is extremely efficient if no exceptions are raised. Actually catching an exception is expensive."),(0,o.kt)("p",null,'To summarize, exceptions are good for rare cases, and conditions are better for frequent use cases. In the end, of course "',(0,o.kt)("a",{parentName:"p",href:"https://en.wikiquote.org/wiki/Grace_Hopper"},"it's better to ask for forgiveness than permission"),'".'),(0,o.kt)("h2",{id:"what-is-an-exception"},"What is an Exception"),(0,o.kt)("p",null,"An exception is an error that happens during execution of a program. When that\nerror occurs, Python generate an exception that can be handled, which avoids your program to crash."),(0,o.kt)("h2",{id:"why-use-exceptions"},"Why use exceptions"),(0,o.kt)("p",null,"Exceptions are convenient in many ways for handling errors and special conditions\nin a program. When you think that you have a code which can produce an error then\nyou can use exception handling."),(0,o.kt)("h2",{id:"raising-an-excpetion"},"Raising an Excpetion"),(0,o.kt)("p",null,"You can raise an exception in your own program by using the raise exception\nstatement."),(0,o.kt)("p",null,"Raising an exception breaks current code execution and returns the exception\nback until it is handled."),(0,o.kt)("h2",{id:"exceptions-1"},"Exceptions"),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"IOError -")," If the file cannot be opened")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ImportError -")," If python cannot find the module")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ValueError -")," Raised when a built-in operation or function receives an argument that has the right type but an inappropriate value")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"KeyboardInterrupt -")," Raised when the user hits the interrupt key (normally Control-C or Delete)")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"EOFError -")," Raised when one of the built-in functions (input() or raw_input()) hits an\nend-of-file condition (EOF) without reading any data"))),(0,o.kt)("h2",{id:"catch-exceptions"},"Catch Exceptions"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},"try:\n    Something here\nexcept Exception as e:\n    print(e)\n")),(0,o.kt)("h2",{id:"catch-requests-exception"},"Catch requests exception"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},'response=requests.request("POST", ZOHO_CREATE_TICKET_URL,data=str(data), headers=headers)\nresponse.raise_for_status()\n\nexcept requests.exceptions.HTTPError as errh:\n    self.message_user(request, "Httperroroccurred,contactadmin %s" %errh, level=messages.ERROR)\n    logger.error(\'HTTPError\', errh)\nexcept requests.exceptions.ConnectionError as errc:\n    self.message_user(request, "Connectionerroroccurred,contactadmin", level=messages.ERROR)\n    logger.error(\'ConnectionError\', errc)\nexcept requests.exceptions.Timeout as errt:\n    self.message_user(request, "Timeout", level=messages.ERROR)\n    logger.error(\'Timeout\', errt)\nexcept requests.exceptions.RequestException as errr:\n    self.message_user(request, "RequestException", level=messages.ERROR)\n    logger.error(\'RequestException\', errr)\nexcept Exception as e:\n    self.message_user(request, "Exceptionoccurred,contactadmin", level=messages.ERROR)\nlogger.error(\'Exception\', e)\n')),(0,o.kt)("h2",{id:"try-catch-finally-block"},"Try Catch Finally block"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-python"},"try:\n    raise KeyboardInterrupt\nexcept KeyboardInterrupt:\n    print('Found keyboard interrupt')\nfinally:\nprint('Goodbye, world!')\n")),(0,o.kt)("h2",{id:"try-catch-else-finally-block"},"Try Catch Else Finally block"),(0,o.kt)("p",null,"The ",(0,o.kt)("inlineCode",{parentName:"p"},"try-except-finally-else")," statement in Python is used to handle and manage errors that can occur during program execution. The ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block is an optional block that is executed when no exceptions are raised in the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block. Here are some scenarios where the ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block can be used:"),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Validation and processing:")," The ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block can be used to process data and perform validation after a successful execution of the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block. For example, you can validate user input in the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block, and if there are no errors, process the input in the ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"File operations:")," The ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block can be used to execute code that is dependent on a file operation succeeding. For example, you can open a file in the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block, and if the file is successfully opened, read its contents in the ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Database operations:")," The ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block can be used to execute code that depends on a successful database operation. For example, you can execute a database query in the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block, and if the query is successful, fetch and process the data in the ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block."))),(0,o.kt)("p",null,"It's important to note that the ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block is executed only if no exceptions are raised in the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block. If an exception is raised, the ",(0,o.kt)("inlineCode",{parentName:"p"},"else")," block is skipped, and the ",(0,o.kt)("inlineCode",{parentName:"p"},"except")," block is executed. The ",(0,o.kt)("inlineCode",{parentName:"p"},"finally")," block, if present, is always executed, regardless of whether an exception is raised or not."),(0,o.kt)("p",null,(0,o.kt)("img",{alt:"image",src:t(86864).Z,width:"2280",height:"1654"})),(0,o.kt)("h2",{id:"raise-exception"},"Raise Exception"),(0,o.kt)("p",null,(0,o.kt)("inlineCode",{parentName:"p"},"raise KeyError(f'body and key not found: {body} {key}')")),(0,o.kt)("h2",{id:"error-vs-exception"},"Error vs Exception"),(0,o.kt)("p",null,"There is a subtle difference between anerrorand anexception."),(0,o.kt)("p",null,"Errors cannot be handled, while Python exceptions can be handled at the run time. An error can be asyntax(parsing) error, while there can be many types of exceptions that could occur during the execution and are not unconditionally inoperable. AnErrormight indicate critical problems that a reasonable application should not try to catch, while anExceptionmight indicate conditions that an application should try to catch. Errors are a form of an unchecked exception and are irrecoverable like anOutOfMemoryError, which a programmer should not try to handle."),(0,o.kt)("p",null,"Exception handling makes your code more robust and helps prevent potential failures that would cause your program to stop in an uncontrolled manner. Imagine if you have written a code which is deployed in production and still, it terminates due to an exception, your client would not appreciate that, so it's better to handle the particular exception beforehand and avoid the chaos."),(0,o.kt)("p",null,"Errors can be of various types:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Syntax Error"),(0,o.kt)("li",{parentName:"ul"},"Out of Memory Error"),(0,o.kt)("li",{parentName:"ul"},"Recursion Error"),(0,o.kt)("li",{parentName:"ul"},"Exceptions")),(0,o.kt)("p",null,(0,o.kt)("a",{parentName:"p",href:"https://www.datacamp.com/community/tutorials/exception-handling-python"},"https://www.datacamp.com/community/tutorials/exception-handling-python")),(0,o.kt)("h2",{id:"built-in-exceptions"},"Built-in Exceptions"),(0,o.kt)("p",null,"BaseException\n+-- SystemExit\n+-- KeyboardInterrupt\n+-- GeneratorExit\n+-- Exception\n+-- StopIteration\n+-- StopAsyncIteration\n+-- ArithmeticError\n| +-- FloatingPointError\n| +-- OverflowError\n| +-- ZeroDivisionError\n+-- AssertionError\n+-- AttributeError\n+-- BufferError\n+-- EOFError\n+-- ImportError\n+-- ModuleNotFoundError\n+-- LookupError\n| +-- IndexError (if the index is out of bounds)\n| +-- KeyError (if the item is not present in the list)\n+-- MemoryError\n+-- NameError\n| +-- UnboundLocalError\n+-- OSError\n| +-- BlockingIOError\n| +-- ChildProcessError\n| +-- ConnectionError\n| | +-- BrokenPipeError\n| | +-- ConnectionAbortedError\n| | +-- ConnectionRefusedError\n| | +-- ConnectionResetError\n| +-- FileExistsError\n| +-- FileNotFoundError\n| +-- InterruptedError\n| +-- IsADirectoryError\n| +-- NotADirectoryError\n| +-- PermissionError\n| +-- ProcessLookupError\n| +-- TimeoutError\n+-- ReferenceError\n+-- RuntimeError\n| +-- NotImplementedError\n| +-- RecursionError\n+-- SyntaxError\n| +-- IndentationError\n| +-- TabError\n+-- SystemError\n+-- TypeError\n+-- ValueError\n| +-- UnicodeError\n| +-- UnicodeDecodeError\n| +-- UnicodeEncodeError\n| +-- UnicodeTranslateError\n+-- Warning\n+-- DeprecationWarning\n+-- PendingDeprecationWarning\n+-- RuntimeWarning\n+-- SyntaxWarning\n+-- UserWarning\n+-- FutureWarning\n+-- ImportWarning\n+-- UnicodeWarning\n+-- BytesWarning\n+-- ResourceWarning"),(0,o.kt)("h2",{id:"references"},"References"),(0,o.kt)("p",null,(0,o.kt)("a",{parentName:"p",href:"http://www.pythonforbeginners.com/error-handling/exception-handling-in-python"},"http://www.pythonforbeginners.com/error-handling/exception-handling-in-python")))}d.isMDXComponent=!0},86864:(e,n,t)=>{t.d(n,{Z:()=>r});const r=t.p+"assets/images/Exceptions-image1-8ee4c7fc630d61572bcb380efb5cd421.jpg"}}]);